using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using SharpCell.Xlsx;

namespace SharpCell.Docs;

internal sealed record ApiPage(Type Type, string Path, string Summary);

internal sealed record ApiOutput(IReadOnlyList<GeneratedFile> Files, IReadOnlyList<ApiPage> Pages);

/// <summary>One Markdown page per public type, from reflection and the XML documentation.</summary>
internal static class ApiReference
{
    private const string Banner = "<!-- Generated by tools/SharpCell.Docs from the XML documentation comments. Do not edit; run the tool with 'generate'. -->";

    private static readonly (string Title, Func<MemberInfo, bool> Belongs)[] Groups =
    [
        ("Constructors", m => m is ConstructorInfo),
        ("Properties", m => m is PropertyInfo),
        ("Methods", m => m is MethodInfo { IsSpecialName: false }),
        ("Operators", m => m is MethodInfo { IsSpecialName: true }),
    ];

    public static IReadOnlyList<Assembly> DocumentedAssemblies() => [typeof(Workbook).Assembly, typeof(XlsxReader).Assembly];

    /// <summary>
    /// The members a page lists: declared, public, without accessors and compiler plumbing. The
    /// members a record gets from the compiler (value equality, <c>ToString</c>, <c>Deconstruct</c>,
    /// the clone behind <c>with</c>) are left out; the record's own summary says it compares by value.
    /// </summary>
    public static IReadOnlyList<MemberInfo> MembersOf(Type type) =>
        type.GetMembers(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly)
            .Where(m => !m.IsDefined(typeof(System.Runtime.CompilerServices.CompilerGeneratedAttribute), false))
            .Where(m => m switch
            {
                MethodInfo method => !method.IsSpecialName || method.Name.StartsWith("op_", StringComparison.Ordinal),
                FieldInfo field => !field.IsSpecialName,
                Type => false,
                _ => true,
            })
            .ToList();

    public static ApiOutput Generate(IReadOnlyList<Assembly> assemblies)
    {
        var docs = XmlDocs.Load(assemblies);
        var types = assemblies.SelectMany(a => a.GetExportedTypes())
            .OrderBy(t => t.Assembly.GetName().Name, StringComparer.Ordinal)
            .ThenBy(t => t.Namespace, StringComparer.Ordinal)
            .ThenBy(t => t.Name, StringComparer.Ordinal)
            .ToList();

        var urls = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var type in types)
        {
            urls[DocId.Of(type)] = $"{type.FullName}.md";
            foreach (var member in MembersOf(type))
                urls[DocId.Of(member)] = $"{type.FullName}.md#{CSharpSignature.Anchor(member)}";
        }

        var missing = types.SelectMany(t => MembersOf(t).Prepend(t)).Select(DocId.Of)
            .Where(id => !docs.Has(id) || docs.Summary(id, _ => null).Length == 0)
            .ToList();
        if (missing.Count > 0)
            throw new DocsException("Public API without a <summary>:\n" + string.Join("\n", missing));

        string? Link(string cref) => urls.GetValueOrDefault(cref);

        var files = new List<GeneratedFile>();
        var pages = new List<ApiPage>();
        foreach (var type in types)
        {
            var path = $"{Generator.ApiDirectory}/{type.FullName}.md";
            files.Add(new GeneratedFile(path, TypePage(type, docs, Link)));
            pages.Add(new ApiPage(type, path, XmlDocs.FirstSentence(docs.Summary(DocId.Of(type), Link))));
        }

        files.Add(new GeneratedFile($"{Generator.ApiDirectory}/index.md", Index(pages)));
        return new ApiOutput(files, pages);
    }

    private static string TypePage(Type type, XmlDocs docs, Func<string, string?> link)
    {
        var id = DocId.Of(type);
        var sb = new StringBuilder();
        sb.Append(Banner).Append("\n\n");
        sb.Append("# ").Append(type.Name).Append("\n\n");
        sb.Append("```csharp\n").Append(CSharpSignature.Declaration(type)).Append("\n```\n\n");
        sb.Append("Namespace `").Append(type.Namespace).Append("` · package `").Append(type.Assembly.GetName().Name).Append("`\n\n");
        Paragraph(sb, docs.Summary(id, link));
        Paragraph(sb, docs.Remarks(id, link));

        var members = MembersOf(type);
        if (type.IsEnum)
        {
            sb.Append("## Values\n\n| Name | Value | Description |\n|---|---|---|\n");
            foreach (var field in members.OfType<FieldInfo>().OrderBy(f => Convert.ToInt64(f.GetRawConstantValue(), System.Globalization.CultureInfo.InvariantCulture)))
            {
                var value = CSharpSignature.Of(field)[(field.Name.Length + 3)..];
                var text = docs.Summary(DocId.Of(field), link).Replace("|", "\\|", StringComparison.Ordinal).Replace("\n\n", " ", StringComparison.Ordinal);
                sb.Append("| <a id=\"").Append(CSharpSignature.Anchor(field)).Append("\"></a>`").Append(field.Name).Append("` | ")
                    .Append(value).Append(" | ").Append(text).Append(" |\n");
            }

            return sb.ToString().TrimEnd() + "\n";
        }

        foreach (var (title, belongs) in Groups)
        {
            var group = members.Where(belongs).OrderBy(CSharpSignature.Heading, StringComparer.Ordinal).ToList();
            if (group.Count == 0)
                continue;
            sb.Append("## ").Append(title).Append("\n\n");
            foreach (var member in group)
                Member(sb, member, docs, link);
        }

        return sb.ToString().TrimEnd() + "\n";
    }

    private static void Member(StringBuilder sb, MemberInfo member, XmlDocs docs, Func<string, string?> link)
    {
        var id = DocId.Of(member);
        sb.Append("<a id=\"").Append(CSharpSignature.Anchor(member)).Append("\"></a>\n");
        sb.Append("### ").Append(CSharpSignature.Heading(member)).Append("\n\n");
        sb.Append("```csharp\n").Append(CSharpSignature.Of(member)).Append("\n```\n\n");
        Paragraph(sb, docs.Summary(id, link));
        Paragraph(sb, docs.Remarks(id, link));

        // <inheritdoc> may bring parameters of another overload; show only this member's own.
        var names = member switch
        {
            MethodBase method => method.GetParameters(),
            PropertyInfo property => property.GetIndexParameters(),
            _ => [],
        };
        var parameters = docs.Parameters(id, link).Where(p => names.Any(n => n.Name == p.Name)).ToList();
        if (parameters.Count > 0)
        {
            sb.Append("**Parameters**\n\n");
            foreach (var (name, text) in parameters)
                sb.Append("- `").Append(name).Append("`: ").Append(text).Append('\n');
            sb.Append('\n');
        }

        if (docs.Returns(id, link) is { Length: > 0 } returns)
            sb.Append("**Returns:** ").Append(returns).Append("\n\n");

        var exceptions = docs.Exceptions(id, link);
        if (exceptions.Count > 0)
        {
            sb.Append("**Exceptions**\n\n");
            foreach (var (name, text) in exceptions)
                sb.Append("- `").Append(name).Append("`: ").Append(text).Append('\n');
            sb.Append('\n');
        }
    }

    private static string Index(IReadOnlyList<ApiPage> pages)
    {
        var sb = new StringBuilder();
        sb.Append(Banner).Append("\n\n# API reference\n\n");
        sb.Append("Every public type of the SharpCell packages. Each page lists the type's members with their C# declarations.\n");
        foreach (var package in pages.GroupBy(p => p.Type.Assembly.GetName().Name))
        {
            sb.Append("\n## ").Append(package.Key).Append("\n\n| Type | Summary |\n|---|---|\n");
            foreach (var page in package)
            {
                sb.Append("| [").Append(page.Type.Name).Append("](").Append(page.Type.FullName).Append(".md) | ")
                    .Append(page.Summary.Replace("|", "\\|", StringComparison.Ordinal)).Append(" |\n");
            }
        }

        return sb.ToString();
    }

    private static void Paragraph(StringBuilder sb, string text)
    {
        if (text.Length > 0)
            sb.Append(text).Append("\n\n");
    }
}
