<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>SharpCell.Docs</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SharpCell.Tests" />
    <PackageReference Include="Markdig" />
    <ProjectReference Include="../../src/SharpCell/SharpCell.csproj" />
    <ProjectReference Include="../../src/SharpCell.Xlsx/SharpCell.Xlsx.csproj" />
  </ItemGroup>
</Project>
