using SharpCell.Docs;

namespace SharpCell.Tests.Docs;

public class ApiReferenceTests
{
    private static readonly ApiOutput Output = ApiReference.Generate(ApiReference.DocumentedAssemblies());

    private static string Page(string path) => Output.Files.Single(f => f.Path == path).Content;

    [Fact]
    public void Every_exported_type_gets_a_page_and_an_index_row()
    {
        var types = ApiReference.DocumentedAssemblies().SelectMany(a => a.GetExportedTypes()).ToList();
        Assert.Equal(types.Count, Output.Pages.Count);
        var index = Page("docs/api/index.md");
        foreach (var type in types)
        {
            Assert.Contains(Output.Files, f => f.Path == $"docs/api/{type.FullName}.md");
            Assert.Contains($"[{type.Name}]({type.FullName}.md)", index);
        }
    }

    [Fact]
    public void A_type_page_has_the_declaration_members_and_their_documentation()
    {
        var page = Page("docs/api/SharpCell.Workbook.md");
        Assert.StartsWith("<!-- Generated by tools/SharpCell.Docs", page);
        Assert.Contains("# Workbook\n", page);
        Assert.Contains("```csharp\npublic sealed class Workbook\n```", page);
        Assert.Contains("## Methods", page);
        Assert.Contains("<a id=\"evaluate-string-cancellationtoken\"></a>\n### Evaluate(string, CancellationToken)", page);
        Assert.Contains("```csharp\npublic CellValue Evaluate(string formula, CancellationToken cancellationToken)\n```", page);
        Assert.Contains("**Exceptions**", page);
        Assert.Contains("- `OperationCanceledException`:", page);
    }

    [Fact]
    public void Enum_values_are_a_table()
    {
        var page = Page("docs/api/SharpCell.ErrorKind.md");
        Assert.Contains("| Name | Value | Description |", page);
        Assert.Contains("| `Div0` | 2 | `#DIV/0!`: division by zero. |", page);
    }

    [Fact]
    public void Inherited_documentation_lists_only_the_member_s_own_parameters()
    {
        var page = Page("docs/api/SharpCell.Xlsx.XlsxReader.md");
        var start = page.IndexOf("### Load(Stream)", StringComparison.Ordinal);
        var section = page[start..page.IndexOf("### Load(string)", StringComparison.Ordinal)];
        Assert.DoesNotContain("`path`", section);
    }

    [Fact]
    public void Links_between_types_point_at_their_pages()
    {
        Assert.Contains("[CellValue](SharpCell.CellValue.md)", Page("docs/api/SharpCell.Cell.md"));
    }
}
