using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using SharpCell.Functions;

namespace SharpCell.Conformance;

internal sealed record FunctionStats(string Name, string Status, string? Deviation, int Cases, int Passed);

/// <summary>
/// The compatibility table: per corpus file and per function, how many compared cells match
/// Excel. Output is deterministic (no timestamps, ordinal sorting) so it can be committed and diffed.
/// </summary>
internal sealed class Report
{
    // Parsed as calls but handled by the evaluator itself rather than the function registry.
    private static readonly HashSet<string> SpecialForms = new(StringComparer.Ordinal) { "LET", "LAMBDA" };

    public Report(IReadOnlyList<FileResult> files)
    {
        Files = [.. files.OrderBy(f => f.File, StringComparer.Ordinal)];
        var cases = new Dictionary<string, (int Cases, int Passed)>(StringComparer.Ordinal);
        foreach (var file in Files)
        {
            foreach (var cell in file.Cells)
            {
                foreach (var function in cell.Functions)
                {
                    var (total, passed) = cases.GetValueOrDefault(function);
                    cases[function] = (total + 1, passed + (cell.Passed ? 1 : 0));
                }
            }
        }

        var names = new SortedSet<string>(cases.Keys, StringComparer.Ordinal);
        foreach (var function in FunctionRegistry.Default.All)
            names.Add(function.Name);

        Functions = [.. names.Select(name =>
        {
            var (total, passed) = cases.GetValueOrDefault(name);
            var (status, deviation) = StatusOf(name);
            return new FunctionStats(name, status, deviation, total, passed);
        })];
    }

    public IReadOnlyList<FileResult> Files { get; }

    public IReadOnlyList<FunctionStats> Functions { get; }

    public int Cells => Files.Sum(f => f.Cells.Count);

    public int Passed => Files.Sum(f => f.Passed);

    private static (string Status, string? Deviation) StatusOf(string name)
    {
        if (SpecialForms.Contains(name))
            return ("implemented", null);
        if (!FunctionRegistry.Default.TryGet(name, out var info))
            return ("not implemented", null);
        return info!.Status switch
        {
            FunctionStatus.Implemented => ("implemented", null),
            FunctionStatus.KnownDeviation => ("known deviation", info.Deviation),
            _ => ("not implemented", null),
        };
    }

    public string ToJson()
    {
        using var stream = new MemoryStream();
        using (var json = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true }))
        {
            json.WriteStartObject();
            json.WriteNumber("cells", Cells);
            json.WriteNumber("passed", Passed);
            json.WriteStartArray("files");
            foreach (var file in Files)
            {
                json.WriteStartObject();
                json.WriteString("file", file.File);
                json.WriteNumber("cells", file.Cells.Count);
                json.WriteNumber("passed", file.Passed);
                json.WriteNumber("skipped", file.Skipped);
                if (file.Error is not null)
                    json.WriteString("error", file.Error);
                json.WriteEndObject();
            }

            json.WriteEndArray();
            json.WriteStartArray("functions");
            foreach (var function in Functions)
            {
                json.WriteStartObject();
                json.WriteString("name", function.Name);
                json.WriteString("status", function.Status);
                if (function.Deviation is not null)
                    json.WriteString("deviation", function.Deviation);
                json.WriteNumber("cases", function.Cases);
                json.WriteNumber("passed", function.Passed);
                json.WriteEndObject();
            }

            json.WriteEndArray();
            json.WriteEndObject();
        }

        return Encoding.UTF8.GetString(stream.ToArray()).ReplaceLineEndings("\n") + "\n";
    }

    public string ToMarkdown()
    {
        var md = new StringBuilder();
        md.Append("# Compatibility\n\n");
        md.Append("Generated by `tools/SharpCell.Conformance` from the reference workbooks in `tests/corpus` ");
        md.Append("(workbooks calculated by Microsoft Excel). Each formula result, and each cell an array formula ");
        md.Append("fills, is recalculated by SharpCell and compared with the value Excel saved: numbers within a ");
        md.Append("relative tolerance of 1e-9 (or the file's own, see `tests/corpus/ironcalc/SOURCE.md`), errors by ");
        md.Append("kind, text exactly. Random functions are compared by result type only.\n\n");
        md.Append(CultureInfo.InvariantCulture, $"**{Passed} of {Cells} cells match Excel ({Percent(Passed, Cells)}).**\n\n");

        var implemented = Functions.Count(f => f.Status == "implemented");
        md.Append("## Functions\n\n");
        md.Append(CultureInfo.InvariantCulture, $"{implemented} implemented, {Functions.Count(f => f.Status == "known deviation")} with a known deviation, ");
        md.Append(CultureInfo.InvariantCulture, $"{Functions.Count(f => f.Status == "not implemented")} used in the corpus but not implemented. ");
        md.Append("A case is a compared cell whose formula uses the function, so a failing case can be caused by another function in the same formula.\n\n");
        md.Append("| Function | Status | Cases | Match | % |\n|---|---|---:|---:|---:|\n");
        foreach (var function in Functions)
        {
            var status = function.Deviation is null ? function.Status : $"{function.Status}: {function.Deviation}";
            md.Append(CultureInfo.InvariantCulture,
                $"| {function.Name} | {Escape(status)} | {function.Cases} | {function.Passed} | {Percent(function.Passed, function.Cases)} |\n");
        }

        md.Append("\n## Files\n\n| File | Cells | Match | % | Note |\n|---|---:|---:|---:|---|\n");
        foreach (var file in Files)
        {
            md.Append(CultureInfo.InvariantCulture,
                $"| {Escape(file.File)} | {file.Cells.Count} | {file.Passed} | {Percent(file.Passed, file.Cells.Count)} | {Escape(file.Error ?? "")} |\n");
        }

        return md.ToString();
    }

    private static string Percent(int part, int whole) =>
        whole == 0 ? "–" : (100.0 * part / whole).ToString("0.0", CultureInfo.InvariantCulture) + "%";

    private static string Escape(string text) => text.Replace("|", "\\|", StringComparison.Ordinal).Replace('\n', ' ');
}
